test dev

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,7 +25,11 @@ jobs:
                         sudo chmod -R 770 /var/www/tafaria-castle
                     fi
                     if [ ! -d ~/tafaria-castle ]; then
-                        git clone https://github.com/goodlifechris/tafaria-castle.git
+                        git clone https://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@github.com/goodlifechris/tafaria-castle.git
+                        if [ $? -ne 0 ]; then
+                            echo "Failed to clone the repository"
+                            exit 1
+                        fi
                     fi
                     cd ~/tafaria-castle
                     git fetch
